name: Cache daily deals
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch & commit
        run: |
          curl -s https://www.gamerpower.com/api/giveaways > cached-deals.json
          git config user.name github-actions
          git config user.email actions@github.com
          git add cached-deals.json
          git commit -m "Update cached deals $(date -u '+%F')" || echo "No changes"
          git push
