name: Auto-update free-game list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run fetch-deals script
        run: node fetch-deals.js

      - name: Commit and push updated cached-deals.json
        run: |
          git config user.name 'actions-user'
          git config user.email 'actions@github.com'
          git add cached-deals.json
          git commit -m "🕒 Auto-update free-game list"
          git push
